name: Report connectors dependency

on:
  pull_request:

jobs:
  report-affected-connectors:
    name: "Report affected connectors"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.
      - name: Extract git-diff changed files
        id: extract_changed_files
        run: |
          git diff --name-only remotes/origin/master...HEAD -- airbyte-integrations/ > ./changed_files.txt
          # Check whether changed_files.txt is not empty
          [[ -s changed_files.txt ]] && echo "changes=true" >> $GITHUB_OUTPUT
      - name: Install dependencies
        if: steps.extract_changed_files.outputs.changes == 'true'
        run: |
          python -m pip install --upgrade pip
      - name: Create dependency report
        if: steps.extract_changed_files.outputs.changes == 'true'
        run: |
          python ./tools/bin/ci_check_dependency.py ./changed_files.txt
      - name: Find existing comment for connector dependencies
        if: steps.extract_changed_files.outputs.changes == 'true'
        uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "report-connectors-dependency.yml"
      - name: Comment report in PR
        if: steps.extract_changed_files.outputs.changes == 'true'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          edit-mode: "replace"
          body-file: "comment_body.md"
