name: Report connectors dependency

on:
  pull_request:

jobs:
  report-affected-connectors:
    name: "Report affected connectors"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Extract git-diff changed files
        run: |
          git diff --name-only remotes/origin/master...HEAD -- airbyte-integrations/ > ./changed_files.txt
        id: extract_changed_files
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Create dependency report
        run: |
          python ./tools/bin/ci_check_dependency.py ./changed_files.txt
      - name: Comment report in PR
#        if: steps.dependency_report.outputs.changed_files_report != ''
#  Always run to check if comment body is working. Should be only if there is a comment_body.md
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-file: "comment_body.md"